name: Build-All-FreeBSD
on: workflow_dispatch

jobs:
  build-all-freebsd:
    name: build-all-freebsd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Startup VM
        uses: cross-platform-actions/action@v0.25.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '14.1'
          architecture: x86_64
          memory: 4G
          cpu_count: 2
          shell: sh
          shutdown_vm: false
          environment_variables: ASSUME_ALWAYS_YES
          run: uname -a

      - name: Install dependencies
        uses: cross-platform-actions/action@v0.25.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '14.1'
          architecture: x86_64
          memory: 4G
          cpu_count: 2
          shell: sh
          shutdown_vm: false
          sync_files: false
          environment_variables: ASSUME_ALWAYS_YES
          run: |
            sudo pkg install -y curl cmake gcc git nasm openjdk17 rust
            pkg info

      - name: Build C++ library
        uses: cross-platform-actions/action@v0.25.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '14.1'
          shell: sh
          cpu_count: 2
          memory: 4G
          shutdown_vm: false
          sync_files: false
          environment_variables: ASSUME_ALWAYS_YES
          run: |
            export JAVA_HOME=/usr/local/openjdk17
            cd core
            pwd
            cmake -B build/release -DCMAKE_BUILD_TYPE=Release
            cmake --build build/release --config Release
            mkdir -p src/main/resources/io/questdb/bin/freebsd-amd64/
            cp target/classes/io/questdb/bin-local/libquestdb.so src/main/resources/io/questdb/bin/freebsd-amd64/

      - name: Build Rust library
        uses: cross-platform-actions/action@v0.25.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '14.1'
          shell: sh
          cpu_count: 2
          memory: 4G
          shutdown_vm: false
          sync_files: false
          environment_variables: ASSUME_ALWAYS_YES
          run: |
            export JAVA_HOME=/usr/local/openjdk17
            cd rust/qdbr
            pwd
            cargo build --release
            cp target/release/libquestdbr.so ../../src/main/resources/io/questdb/bin/freebsd-amd64/

      - name: Shutdown VM
        uses: cross-platform-actions/action@v0.25.0
        env:
          ASSUME_ALWAYS_YES: yes
        with:
          operating_system: freebsd
          version: '14.1'
          shell: sh
          memory: 4G
          cpu_count: 2
          sync_files: false
          shutdown_vm: true
          environment_variables: ASSUME_ALWAYS_YES
          run: true
